/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverviewSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            ok: true;
        };
        AmountCount: {
            /** Format: int64 */
            count: number;
            total_amount: number;
            currency: string;
        };
        UnbilledTime: {
            /** Format: int64 */
            total_duration: number;
            total_amount: number;
            /** Format: int64 */
            project_count: number;
            currency: string;
        };
        Count: {
            /** Format: int64 */
            count: number;
        };
        CashBalance: {
            total_balance: number;
            currency: string;
            /** Format: int64 */
            account_count: number;
        };
        OverviewSummary: {
            open_invoices: components["schemas"]["AmountCount"];
            unbilled_time: components["schemas"]["UnbilledTime"];
            inbox_pending: components["schemas"]["Count"];
            transactions_to_review: components["schemas"]["Count"];
            cash_balance: components["schemas"]["CashBalance"];
            /** Format: int64 */
            runway: number;
        };
    };
    responses: {
        /** @description Missing, invalid, or expired Supabase session JWT */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getOverviewSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team-scoped overview metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
